### ISSUE TITLE
Flush logs when the server process is killed manually

### ISSUE THREAD

**Issue by spacemud** [Sphinxila/samp-plugin-spdlog#1]
I note that when the server crashes, the logs are flushed before the crash occurs. Would it be possible to extend this behaviour to when the server process is killed manually? As it stands, killing the process doesn't result in the logs being flushed, which can make development a pain.

**Comment by philip1337** [comment]
Depends how the interrupt happens and its also plattform dependent.
I will give you a feedback as soon as I test it.

**Comment by philip1337** [comment]
As I now there is no solution to catch the TerminateProcess (taskkill) event for windows.
The signal handler SIGSEGV should work for linux.
