### ISSUE TITLE
whats wrong?

### ISSUE THREAD

**Issue by Dayvison** [Sphinxila/samp-plugin-spdlog#6]
```c++
#include <a_samp>
#include <a_spdlog>

main() {
    LoggerSetAsyncMode(4096);
	BasicLogger("test", "scriptfiles/test.txt");
	ConsoleLogger("stdout");

	LoggerSetLevel(TRACE);
	LogCritical("stdout", "work");
	LogInfo("stdout", "work");
	LogInfo("test", "not work");
	LogCritical("test", "not work");

	SetTimer("close", 1000, false);
}
forward close();public close(){ SendRconCommand("exit"); }
```

This don't work on Ubuntu 14.04.5 LTS and Windows 10

**Comment by philip1337** [comment]
I will check that soon.

**Comment by philip1337** [comment]
Hey dude, 
sorry foor the long fix time, was on holiday and had to do some other stuff.

Now it should work fine.
I added some more log output if something wents wrong.

https://github.com/Sphinxila/samp-plugin-spdlog/commit/67d48eea7ddd03e759c108cf33a0077e09be3787

Kind regards
Sphinx
